### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by itaditya** [itaditya/squid-logs#2]
- [ ] Setup end to end types and fix all TS alerts.
- [ ] Change API request & response fields to camelCase format. Only db will have snake_case.
- [ ] use [Action Listener middleware](https://www.npmjs.com/package/@rtk-incubator/action-listener-middleware) to show API error toasts for any rejected actions from createAsyncThunk.
- [ ] Login credentials picker.
- [ ] Logged in organiser details with [Avatar](https://www.radix-ui.com/docs/primitives/components/avatar) etc.
- [ ] Implement Login with phone end to end.
- [ ] Create GitHub Action to run `tsc` on PRs.
- [ ] Create pre-commit hook to run `prettier` & pre-push hook to run `tsc`.
- [ ] Elimination Timeline UI.
- [ ] Participant Detail UI ([HoverCard](https://www.radix-ui.com/docs/primitives/components/hover-card)).
- [ ] UI tests with mocked APIs (msw).
- [ ] Animations with framer-motion.
